const { Client, Environment } = require('square');
const crypto = require('crypto');

// Initialize Square Client
const squareClient = new Client({
  environment: process.env.SQUARE_ENVIRONMENT === 'production' ? Environment.Production : Environment.Sandbox,
  accessToken: process.env.SQUARE_ACCESS_TOKEN || 'sandbox-sq0cgb-...',
});

const { paymentsApi, checkoutApi } = squareClient;

/**
 * Charge a Square payment using a secure nonce generated by the mobile app.
 * @param {string} sourceId - The payment nonce (or card ID).
 * @param {number} amountCents - Amount to charge in cents.
 * @param {string} currency - Currency code (e.g. 'USD').
 * @param {string} orderId - Application order ID for tracking.
 */
async function processSquarePayment(sourceId, amountCents, currency = 'USD', orderId) {
  try {
    const idempotencyKey = crypto.randomUUID();

    const response = await paymentsApi.createPayment({
      sourceId: sourceId,
      idempotencyKey: idempotencyKey,
      amountMoney: {
        amount: BigInt(amountCents),
        currency: currency,
      },
      referenceId: orderId,
      note: `Order ${orderId}`,
    });

    return {
      success: true,
      paymentId: response.result.payment.id,
      status: response.result.payment.status,
      receiptUrl: response.result.payment.receiptUrl,
    };
  } catch (error) {
    console.error('Square Payment Error:', error);
    if (error.errors) {
      const errorMessage = error.errors.map((e) => e.detail).join(', ');
      throw new Error(`Square error: ${errorMessage}`);
    }
    throw error;
  }
}

/**
 * Create a Square Checkout Link for Web-based subscription payments.
 */
async function createSubscriptionCheckout(userId, planTier, amountCents) {
  try {
    const idempotencyKey = crypto.randomUUID();
    
    const response = await checkoutApi.createPaymentLink({
      idempotencyKey,
      order: {
        locationId: process.env.SQUARE_LOCATION_ID || 'sandbox-location',
        referenceId: `${userId}|${planTier}`, // Pipe separated to parse in webhook
        lineItems: [
          {
            name: `R3sults ${planTier} Subscription`,
            quantity: '1',
            basePriceMoney: {
              amount: BigInt(amountCents),
              currency: 'USD',
            },
          },
        ],
      },
      checkoutOptions: {
        redirectUrl: 'r3sults://subscription/success',
      }
    });

    return response.result.paymentLink.url;
  } catch (error) {
    console.error('Square Checkout Error:', error);
    if (error.errors) {
      const errorMessage = error.errors.map((e) => e.detail).join(', ');
      throw new Error(`Square error: ${errorMessage}`);
    }
    throw error;
  }
}

module.exports = {
  squareClient,
  processSquarePayment,
  createSubscriptionCheckout,
};
